// Example usage of gleam-codegen
// Demonstrates the current API capabilities

import gleam/io
import gleam_codegen as gc
import gleam_codegen/op

pub fn main() {
  io.println("=== Gleam Codegen Examples ===")

  basic_expressions_example()
  operator_examples()
  complex_expressions_example()
  file_generation_example()
}

fn basic_expressions_example() {
  io.println("\n1. Basic Expressions:")

  // Create basic literals
  let number = gc.int(42)
  let text = gc.string("Hello, Gleam!")
  let flag = gc.bool(True)
  let nothing = gc.nil()
  let var = gc.variable("my_variable")

  io.println("  ✓ Created literals: int, string, bool, nil")
  io.println("  ✓ Created variable reference")

  // These expressions are now properly typed and structured
  let _expressions = [number, text, flag, nothing, var]
}

fn operator_examples() {
  io.println("\n2. Operator Examples:")

  let x = gc.int(10)
  let y = gc.int(5)
  let a = gc.bool(True)
  let b = gc.bool(False)

  // Arithmetic
  let sum = op.plus(x, y)
  let difference = op.minus(x, y)
  let product = op.multiply(x, y)
  let quotient = op.divide(x, y)
  let remainder = op.modulo(x, y)

  io.println("  ✓ Arithmetic: +, -, *, /, %")

  // Comparison
  let equal = op.equal(x, y)
  let not_equal = op.not_equal(x, y)
  let less = op.lt(x, y)
  let greater = op.gt(x, y)
  let less_eq = op.lte(x, y)
  let greater_eq = op.gte(x, y)

  io.println("  ✓ Comparison: ==, !=, <, >, <=, >=")

  // Logical
  let and_op = op.and(a, b)
  let or_op = op.or(a, b)

  io.println("  ✓ Logical: &&, ||")

  // String concatenation
  let hello = gc.string("Hello, ")
  let world = gc.string("World!")
  let greeting = op.append(hello, world)

  io.println("  ✓ String concatenation: <>")

  // Pipes
  let piped = op.pipe(x, gc.variable("some_function"))
  let reverse_piped = op.pipe_left(gc.variable("other_function"), y)

  io.println("  ✓ Pipe operators: |>, <|")

  let _all_ops = [
    sum,
    difference,
    product,
    quotient,
    remainder,
    equal,
    not_equal,
    less,
    greater,
    less_eq,
    greater_eq,
    and_op,
    or_op,
    greeting,
    piped,
    reverse_piped,
  ]
}

fn complex_expressions_example() {
  io.println("\n3. Complex Expressions:")

  let a = gc.int(10)
  let b = gc.int(20)
  let c = gc.int(30)

  // Nested arithmetic: (a + b) * c
  let complex1 = op.multiply(op.plus(a, b), c)

  // Chained operations: a + b + c
  let complex2 = op.plus(op.plus(a, b), c)

  // Mixed operations: (a > b) && (c != 0)
  let complex3 = op.and(op.gt(a, b), op.not_equal(c, gc.int(0)))

  // Function call with operations
  let func_call =
    gc.call(gc.variable("calculate"), [op.plus(a, b), op.multiply(c, gc.int(2))])

  io.println("  ✓ Nested arithmetic expressions")
  io.println("  ✓ Chained operations")
  io.println("  ✓ Mixed logical and comparison")
  io.println("  ✓ Function calls with expression arguments")

  let _complex_expressions = [complex1, complex2, complex3, func_call]
}

fn file_generation_example() {
  io.println("\n4. File Generation:")

  // Create some expressions
  let value1 = gc.add(gc.int(42), gc.int(8))
  let value2 = gc.string("Generated by gleam-codegen!")

  // Create declarations
  let decl1 = gc.declaration("magic_number", value1)
  let decl2 = gc.declaration("message", value2)

  // Create a file
  let my_file = gc.file(["generated_module"], [decl1, decl2])

  // Convert to string (currently a placeholder)
  let file_content = gc.to_string(my_file)

  io.println("  ✓ Created declarations")
  io.println("  ✓ Generated file structure")
  io.println("  ✓ File content: " <> file_content)
  io.println("  ⚠ Note: Full code rendering not yet implemented")
}
